### ISSUE TITLE
Bluetooth Applet disappear from systray after resume from suspend.

### ISSUE THREAD

**Issue by queeup** [linuxmint/cinnamon-bluetooth#15]
Bluetooth Applet disappear from systray after resume from suspend. But bluetooth devices working OK. Just applet disappear.

```
cinnamon                          2.4.5+rebecca         amd64
cinnamon-bluetooth                3.8.7+rebecca         amd64
```

**Comment by queeup** [comment]
Problem still exist.

```
cinnamon                          2.6.13+rafaela        amd64
cinnamon-bluetooth                3.8.8+rafaela         amd64
```

**Comment by atomi** [comment]
Same problem. Another interesting thing that happens is that occasionally the applet itself just doesn't appear when you click on the system tray icon. Restart is always required. I tried ```apt-get remove --purge``` and reinstalling but the issue persists.

**Comment by queeup** [comment]
With kernel 4 and above not happening. I am going to close this. I guess it's a kernel issue.
