### ISSUE TITLE
gnome-bluetooth 3.10 support

### ISSUE THREAD

**Issue by paprykut** [linuxmint/cinnamon-bluetooth#4]
Gnome-bluetooth has changed its API and as of the Gnome 3.10 release it does not support GnomeBluetoothApplet(). Instead, it now uses the BluetoothClient to detect connected services (see https://bugzilla.gnome.org/show_bug.cgi?id=719341 and https://bug719341.bugzilla-attachments.gnome.org/attachment.cgi?id=262859). As the direct result of this, the Cinnamon bluetooth applet does not load. Instead, it drops an error about GnomeBluetoothApplet being unrecognized.

There are two possible solutions:
1) the preffered one is to patch the current applet.js and make it use the new API; 
2) or, as a temporary workaround, gnome-bluetooth still ships with the relevant libs that would need to be manually linked to appropriate places (ugly solution):

```sh
cd /usr/lib
ln -s gnome-bluetooth/libgnome-bluetooth-applet.so.0 .
ln -s gnome-bluetooth/GnomeBluetoothApplet-1.0.typelib girepository-1.0
```

**Comment by clefebvre** [comment]
Closing the issue, we'll consider PRs.
