### ISSUE TITLE
Build fails on Arch Linux (with Gnome 3.12) due to API changes

### ISSUE THREAD

**Issue by pmarcelll** [linuxmint/cinnamon-bluetooth#9]
This is the error message from make:

```
Making all in bluetooth
make[3]: Entering directory '/tmp/yaourt-tmp-marcell/aur-cinnamon-bluetooth-git/src/cinnamon-bluetooth/panels/bluetooth'
  CC       cc-bluetooth-panel.lo
cc-bluetooth-panel.c:35:34: fatal error: bluetooth-killswitch.h: No such file or directory
 #include <bluetooth-killswitch.h>
                                  ^
compilation terminated.
```
I've found a message on the Gnome mailing-list about the changes:
https://mail.gnome.org/archives/commits-list/2013-December/msg01069.html

**Comment by oddityoverseer13** [comment]
Any word on when this will get fixed? I also just installed Antergos, and I'm sad to see it doesn't currently include bluetooth support.

**Comment by monsta** [comment]
http://segfault.linuxmint.com/2015/03/blueberry/

**Comment by pmarcelll** [comment]
It's available in AUR, so I'm closing it :+1:
